[package]
name = "cita-sm2"
version = "0.1.0"
authors = ["Cryptape Technologies <arch@cryptape.com>"]

[dependencies]
lazy_static = "0.2"
rustc-serialize = "0.3"
serde = "1.0"
bincode = "0.8"
util = { path = "../util" }
rlp = { path = "../rlp" }

[features]
default = []
sha3hash = ["util/sha3hash"]
blake2bhash = ["util/blake2bhash"]
sm3hash = ["util/sm3hash"]
