[package]
name = "pubsub_rabbitmq"
version = "0.1.0"
authors = ["Cryptape Technologies <contact@cryptape.com>"]

[dependencies.amqp]
version = "0.1"
default-features = false

[dependencies]
message_queue = { path = "../message_queue" }
