[package]
name = "util"
version = "0.6.0"
authors = ["Parity Technologies <admin@parity.io>", "Cryptape Technologies <contact@cryptape.com>"]

[dependencies]
hashable = { path = "../hashable" }
logger = { path = "../logger" }
rustc-hex = "1.0"
rand = "0.3.12"
time = "0.1.34"
elastic-array = "0.9"
rlp = { path = "../rlp" }
heapsize = "0.4"
itertools = "0.5"
vergen = "0.1"
target_info = "0.1"
cita-types = { path = "../cita-types" }
snappy = { path = "../snappy" }
parking_lot = "0.6"
ansi_term = "0.9"
tiny-keccak= "1.4"
ethcore-bloom-journal = { path = "../ethcore-bloom-journal" }
regex = "1.0.5"
lru-cache = "0.1.0"
panic_hook = {path = "../panic_hook"}
serde = "1.0"
serde_derive = "1.0"
toml = "0.4"
git2 = "0.7"
rustc_version = "0.2.0"

[features]
default = []
sha3hash = ["hashable/sha3hash"]
blake2bhash = ["hashable/blake2bhash"]
sm3hash = ["hashable/sm3hash"]

[dev-dependencies]
mktemp = "0.3.1"
