[package]
name = "util"
version = "0.6.0"
authors = ["Parity Technologies <admin@parity.io>", "Cryptape Technologies <contact@cryptape.com>"]

[dependencies]
blake2b = { path = "../blake2b", optional = true }
libsm = { git = "https://github.com/cryptape/libsm", rev = "ac323abd3512a9fdb8bfd6cd349a6fc46deb688f", optional = true }
logger = { path = "../logger" }
rustc-hex = "1.0"
rand = "0.3.12"
time = "0.1.34"
parity-rocksdb = "0.5"
elastic-array = "0.9"
rlp = { path = "../rlp" }
rlp_derive = { path = "../rlp_derive" }
heapsize = "0.4"
itertools = "0.5"
clippy = {version = "0.0.175", optional = true}
libc = "0.2.7"
vergen = "0.1"
target_info = "0.1"
cita-types = { path = "../cita-types" }
parking_lot = "0.6"
ansi_term = "0.9"
tiny-keccak= "1.4"
ethcore-bloom-journal = { path = "../ethcore-bloom-journal" }
regex = "1.0.5"
lru-cache = "0.1.0"
uuid = { version = "0.7", features = ["v4"] }
panic_hook = {path = "../panic_hook"}
serde = "1.0"
serde_derive = "1.0"
toml = "0.4"
git2 = "0.7"
rustc_version = "0.2.0"

[features]
default = []
sha3hash = []
blake2bhash = ["blake2b"]
sm3hash = ["libsm"]

[dev-dependencies]
mktemp = "0.3.1"
