[package]
name = "cita-common-benches"
version = "0.1.0"
authors = ["Cryptape Technologies <contact@cryptape.com>"]
edition = "2018"

[dependencies]
rand = "0.4"

[dev-dependencies]
criterion = "0.2"
tiny-keccak= "1.4"
blake2b = { path = "../blake2b" }
secp256k1 = {version = "0.12", features = ["rand"]}
sodiumoxide = "0.1.0"
libsm = { git = "https://github.com/cryptape/libsm", rev = "ac323abd3512a9fdb8bfd6cd349a6fc46deb688f" }

[[bench]]
name = "hash-algos"
harness = false

[[bench]]
name = "sign-algos"
harness = false
