[package]
name = "cita-web3"
version = "0.1.0"
authors = ["Rivtower Technologies <arch@citahub.com>"]
license = "Apache-2.0"

[dependencies]
jsonrpc-types = { path = "../jsonrpc-types" }
web3 = "0.18.0"

[features]
default = []
