[package]
name = "logger"
version = "0.1.0"
authors = ["Cryptape Technologies <contact@cryptape.com>"]

[dependencies]
log = "0.4.3"
log4rs = "0.8"
crossbeam-channel = "0.2"
signal-hook = "0.1"
chrono = "0.4"
libc = "~0.2"
