[package]
name = "logger"
version = "0.1.0"
authors = ["Cryptape Technologies <arch@cryptape.com>"]

[dependencies]
log = "0.4"
log4rs = "0.8"
chan-signal = "0.3"
chrono = "0.4"

[features]
default = []
console = []
