[package]
description = "proto"
name = "libproto"
version = "0.6.0"
authors = ["Cryptape Technologies <contact@cryptape.com>"]

[dependencies]
protobuf = { version = "2.0.4", features = ["with-bytes"]}
cita-types = { path = "../cita-types" }
cita-crypto = { path = "../cita-crypto" }
hashable = { path = "../hashable" }
util = { path = "../util" }
rustc-serialize = "0.3"
rlp = { path = "../rlp" }
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
logger = { path = "../logger" }
grpc = "0.5.0"
tls-api = "0.1.14"

[features]
default = []
secp256k1 = ["cita-crypto/secp256k1"]
ed25519 = ["cita-crypto/ed25519"]
sm2 = ["cita-crypto/sm2"]
sha3hash = ["hashable/sha3hash", "util/sha3hash"]
blake2bhash = ["hashable/blake2bhash", "util/blake2bhash"]
sm3hash = ["hashable/sm3hash", "util/sm3hash"]
