[package]
name = "jsonrpc-types"
version = "0.1.0"
authors = ["Cryptape Technologies <contact@cryptape.com>"]

[dependencies]
jsonrpc-types-internals = { path = "internals" }
cita-types = { path = "../cita-types" }
logger = { path = "../logger" }
libproto = { path = "../libproto" }
proof = { path = "../proof" }
bincode = "0.8"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
rustc-serialize = "0.3"
uuid = { version = "0.7", features = ["v4"] }

[features]
default = []
secp256k1 = ["libproto/secp256k1", "proof/secp256k1"]
ed25519 = ["libproto/ed25519", "proof/ed25519"]
sm2 = ["libproto/sm2", "proof/sm2"]
sha3hash = ["libproto/sha3hash", "proof/sha3hash"]
blake2bhash = ["libproto/blake2bhash", "proof/blake2bhash"]
sm3hash = ["libproto/sm3hash", "proof/sm3hash"]
